MIN_STORY_PAGES = 16
MAX_STORY_PAGES = 48
MAX_STORY_PANELS = 96
MIN_PANELS_PER_PAGE = 1
MAX_PANELS_PER_PAGE = 4
MAX_IMAGES_PER_BATCH = 24
MAX_IMAGES_PER_STORY = 96
MAX_VARIANTS_PER_PANEL = 4


def page_count_in_range(page_count: int) -> bool:
    return MIN_STORY_PAGES <= page_count <= MAX_STORY_PAGES
